version: '3.8'
services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:5173"
    volumes:
      - ./Client:/app
      - /app/node_modules
    networks:
      - eap-network

  api:
    build: ./API
    container_name: "api"
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./API:/app
    depends_on:
      - db
    networks:
      - eap-network

  db:
    image: mysql:8.0
    container_name: "db"
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - eap-network

networks:
  eap-network:

volumes:
  db_data: